name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'tModLoader version'
        required: true
        type: string
      PRERELEASE:
        description: 'If the release is a pre-release'
        required: true
        type: boolean
    secrets:
      DOCKER_PASSWORD:
        required: true
      GHCR_PASSWORD:
        required: true

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: passivelemon
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push Docker image (Pre-release)
        uses: docker/build-push-action@v6
        if: ${{ github.event.inputs.PRERELEASE == true }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: VERSION=${{ github.event.inputs.VERSION }}
          tags: |
            passivelemon/tmodloader1.4-docker:latest-2024-pre
            passivelemon/tmodloader1.4-docker:${{ github.event.inputs.VERSION }}
            ghcr.io/passivelemon/tmodloader1.4-docker:latest-2024-pre
            ghcr.io/passivelemon/tmodloader1.4-docker:${{ github.event.inputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (Release)
        uses: docker/build-push-action@v6
        if: ${{ github.event.inputs.PRERELEASE == false }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: VERSION=${{ github.event.inputs.VERSION }}
          tags: |
            passivelemon/tmodloader1.4-docker:latest
            passivelemon/tmodloader1.4-docker:latest-2024
            passivelemon/tmodloader1.4-docker:${{ github.event.inputs.VERSION }}
            ghcr.io/passivelemon/tmodloader1.4-docker:latest
            ghcr.io/passivelemon/tmodloader1.4-docker:latest-2024
            ghcr.io/passivelemon/tmodloader1.4-docker:${{ github.event.inputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

